### ISSUE TITLE
Issue with routing railways

### ISSUE THREAD

**Issue by guidoeco** [gaulinmp/pyroutelib2#2]
I can't get routing for train journeys to work, that is calling the LoadOSM("train"). 

Having had a look I think this is because the weight variable in the loadOsm.py always seems to be set to 0.0 as it is called with the highway rather than highway and/or railway option. Or I being daft and have missed something obvious?

The following patch which concatenates the railway and highway strings variables seems to fix the issue:

diff --git a/loadOsm.py b/loadOsm.py
index e149ad9..08f0f0a
--- a/loadOsm.py
+++ b/loadOsm.py
@@ -123,7 +123,7 @@ class LoadOsm:
       (node_id,x,y) = node
       if last[0]:
         if(access[self.transport]):
-          weight = self.weights.get(self.transport, highway)
-          weight = self.weights.get(self.transport, (railway + highway))
         self.addLink(last[0], node_id, weight)
         self.makeNodeRouteable(last)
         if reversible or self.transport == 'foot':

**Comment by gaulinmp** [comment]
What about: `weight = self.weights.get(self.transport, highway or railway)` instead? That way the order is self.transport -> highway -> railway? Or do you think `railway or highway` would be better?

**Comment by guidoeco** [comment]
This is a good point. I'll test how "railway or highway" and "highway or railway" maps my current use case. 

Given this. I think "cycle/walk to train station, take train, cycle/walk. Bus/taxi only if it's too far to walk" would be:

weight = self.weights.get(self.transport, railway or highway)

Although I am aware this is not everyone's preference to the point I have been described as a "public-transport fetishist..."

**Comment by guidoeco** [comment]
I've tested this for a return journey on a 40 mile route and found no difference between the two 'or' and '+'  Given this, my (minimal) preference would be: railway or highway
